<?php

class Factory extends \Illuminate\Validation\Factory
{
    public function make(array $data, array $rules, array $messages = [], array $customAttributes = [])
    {
        $messages = require __DIR__ . '/zh-CN.php';
        return parent::make($data, $rules, $messages, $customAttributes); // TODO: Change the autogenerated stub
    }
}